[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "devops_5toc"
version = "1.0.0"
description = "Proyecto CI/CD en Python"
authors = [
    { name = "Ricardo Astudillo" }
]
dependencies = []
