[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "devops_5toc_mayte"
version = "1.0.0"
description = "Proyecto CI/CD - Mayte Anchapanta"
authors = [
    { name = "Mayte Anchapanta" }
]
dependencies = []